# Generated by Django 6.0 on 2025-12-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_tamanho_produto_tamanhos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('desconto_porcentagem', models.IntegerField(verbose_name='Desconto (%)')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
